return {
    -----------------------------------------------------------------
    --- 1. INTELLIGENCE (LSP) - The "Brain"
    --- Uses clangd with teh compiation database generated by CMake
    -----------------------------------------------------------------
    {
        "neovim/nvim-lspconfig",
        opts = {
            servers = {
                clangd = {
                    -- "background-index" speeds up large projects (QT/VTK)
                    -- "clang-tidy" enables static analysis checks inline
                    --
                    cmd = { "clangd", "--background-index", "--clang-tidy", "--header-insertion=iwyu" },
                    init_options = {
                        fallbackFlags = { "-std=c++20" },
                    },
                },
            },
        },
    },

    -----------------------------------------------------------------
    --- 2. ORCHESTRATION (Task Runner) - Ther "Manager"
    -----------------------------------------------------------------

    {
        "stevearc/overseer.nvim",
        opts = {
            task_list = {
                direction = "bottom",
                min_height = 10,
                default_detail = 1,
            },
        },
        config = function(_, opts)
            local overseer = require("overseer")
            overseer.setup(opts)

            -- CUSTOM PROVIDER: Dynamically reads your justfile
            -- This ensures that if you add "just deploy" later, it automatically appers here .
            overseer.register_template({
                name = "Justfile jrecipes",
                generator = function(opts, cb)
                    local output = vim.fn.system("just --summary")
                    local recipes = vim.split(output, "%s+", { trimempty = true })
                    local ret = {}

                    for _, recipe in ipairs(recipes) do
                        table.insert(ret, {
                            name = "⚡ " .. recipe,
                            params = {},
                            builder = function()
                                return {
                                    cmd = { "just", recipe },
                                    strategy = {
                                        "jobstart",
                                        use_terminal = false,
                                    },
                                    components = {
                                        "default",
                                        {
                                            "on_output_parse",
                                            problem_matcher = { "$gcc" },
                                            relative_file_root = vim.fn.getcwd(),
                                        },
                                        { "on_output_quickfix", open = true },

                                        "unique",
                                    },
                                }
                            end,
                        })
                    end
                    cb(ret)
                end,
            })
        end,
        keys = {
            { "<leader>rr", "<cmd>OverseerRun<cr>", desc = "Run Task (just)" },
            { "<leader>ro", "<cmd>OverseerToggle", desc = "Toggle Task Output" },
            {
                "<leader>rd",
                function()
                    require("overseer").run_template({ name = "⚡ default" })
                end,
                desc = "Run Default (just)",
            },
            {
                "<leader>ri",
                function()
                    require("overseer").run_template({ name = "⚡ init" })
                end,
                desc = "Run init (just)",
            },
            {
                "<leader>rc",
                function()
                    require("overseer").run_template({ name = "⚡ clean" })
                end,
                desc = "Run clean (just)",
            },
        },
    },
    {
        "mfussenegger/nvim-dap",
        optional = true,
        dependencies = {
            "mason-org/mason.nvim",
            "jay-babu/mason-nvim-dap.nvim",
        },
        opts = function()
            local dap = require("dap")

            local function get_binary_path()
                local cwd = vim.fn.getcwd()
                local possible_paths = {
                    cwd .. "/build/debug/FlowLearning",
                    cwd .. "/build/release/FlowLearning",
                    cwd .. "/build/FlowLearning",
                }
                for _, p in ipairs(possible_paths) do
                    if vim.fn.filereadable(p) == 1 then
                        return p
                    end
                end
                return vim.fn.input("Path to executable: ", cwd .. "/build/", "file")
            end

            dap.adapters.codelldb = {
                type = "server",
                port = "${port}",
                executable = {
                    command = "codelldb",
                    args = { "--port", "${port}" },
                },
            }

            dap.configurations.cpp = {
                {
                    name = "Debug (just Built)",
                    type = "codelldb",
                    request = "launch",
                    program = get_binary_path,
                    cwd = "${workspaceFolder}",
                    stopOnEntry = false,
                },
            }
        end,
    },
}
